let path = window.location.origin === 'http://localhost:3000' ? '/' : 'Metriker/';
let graphData = {
    nodes: [
        {
            id: 0,
            title: 'Ievgenii Spitsyn',
            radius: 50,
            color: '#1977f2',
            opacity: 1,
            type: 'circle',
            fx: window.innerWidth / 2,
            fy: window.innerHeight / 2,
            texture: {
                id: 0,
                path: path + 'cv/img/profile.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'profile',
                webGlType: 'mono' // webGl shader parameter affecting alpha blending could be mono or complex
            },
            description: ['Ievgenii Spitsyn', 'Age: 33', 'Country: Ukraine', 'Mail: ievgeny.s@gmail.com', 'Twitter: IevgeniiSp', 'LinkedIn: spitsyn-ievgenii-3b8a656a', 'I turn data into visual stories that reveal their true value. Enthusiastic traveler, visited 34 countries.']
        },
        // Engineering toolkit
        {
            id: 1,
            title: 'Engineering toolkit',
            radius: 50,
            color: '#f41900',
            opacity: 1,
            type: 'circle',
            fx: window.innerWidth / 2 - 300,
            fy: window.innerHeight / 2 - 150,
            texture: {
                id: 1,
                path: path + 'cv/img/technologies.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'profile',
                webGlType: 'mono'
            },
            description: ['Libraries and tools that I use in my work most of the time.']
        },
        {
            id: 2,
            title: 'React + Redux + MobX',
            radius: 25,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['6 years experience', 'Common projects:', 'Complex dashboards, GUI interfaces, Analytical systems']
        },
        {
            id: 3,
            title: 'WebGl',
            radius: 15,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['4 years experience', 'Common projects:', 'High speed Graphs', '3D interactive widgets', 'Maps + interactive layers']
        },
        {
            id: 4,
            title: 'ThreeJs',
            radius: 20,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['3 years experience', 'Common ppojects:', 'High speed Graphs', '3D interactive widgets', 'Maps + interactive layers']
        },
        {
            id: 5,
            title: 'Angular',
            radius: 15,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['2 years experience', 'Common projects:', 'Complex user interfaces', 'Interactive GUI']
        },
        {
            id: 6,
            title: 'D3',
            radius: 20,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            texture: {
                id: 2,
                path: path + 'cv/img/d3.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'd3',
                webGlType: 'mono'
            },
            description: ['8 years experience', 'Common projects:', 'Various charts', 'Integration with WebGL/Canvas', 'Interactive dashboards']
        },
        {
            id: 7,
            title: 'Postgres',
            radius: 15,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['2 years experience']
        },
        {
            id: 8,
            title: 'GraphGl',
            radius: 15,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['1 year experience']
        },
        {
            id: 9,
            title: 'Node',
            radius: 15,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['3 years experience']
        },
        {
            id: 10,
            title: 'JS/HTML/CSS/SASS',
            radius: 25,
            color: '#de564e',
            opacity: 1,
            type: 'circle',
            description: ['10 years experience']
        },
        // Infrastructure & management tools
        {
            id: 11,
            title: 'Infrastructure & management tools',
            radius: 50,
            color: '#f41900',
            opacity: 1,
            type: 'circle',
            fx: window.innerWidth / 2 + 300,
            fy: window.innerHeight / 2 + 150,
            texture: {
                id: 3,
                path: path + 'cv/img/infrastructure.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'profile',
                webGlType: 'mono'
            },
            description: ['Infrastructure & management instruments used in everyday work']
        },
        {
            id: 12,
            title: 'Jenkins',
            radius: 20,
            color: '#944ab3',
            opacity: 1,
            type: 'circle',
            description: ['6 years experience', 'Write Jekins config files', 'Configure Jenkins']
        },
        {
            id: 13,
            title: 'Docker',
            radius: 20,
            color: '#944ab3',
            opacity: 1,
            type: 'circle',
            description: ['4 years experience', 'Create and congigure Docker containers']
        },
        {
            id: 14,
            title: 'Jira',
            radius: 25,
            color: '#944ab3',
            opacity: 1,
            type: 'circle',
            description: ['8 years experience']
        },
        {
            id: 15,
            title: 'GitHub/Bitbucket',
            radius: 25,
            color: '#944ab3',
            opacity: 1,
            type: 'circle',
            description: ['10 years experience']
        },
        {
            id: 16,
            title: 'WebStorm',
            radius: 25,
            color: '#944ab3',
            opacity: 1,
            type: 'circle',
            texture: {
                id: 4,
                path: path + 'cv/img/webstorm.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'profile',
                webGlType: 'mono'
            },
            description: ['8 years experience']
        },
        // Leadership && selling skills
        {
            id: 17,
            title: 'Leadership && selling projects',
            radius: 50,
            color: '#f41900',
            opacity: 1,
            type: 'circle',
            fx: window.innerWidth / 2 + 300,
            fy: window.innerHeight / 2 - 150,
            texture: {
                id: 5,
                path: path + 'cv/img/leadership.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'leadership',
                webGlType: 'mono'
            },
            description: ['Business responsibilities, roles and achievements.']
        },
        {
            id: 18,
            title: 'Tech Lead role',
            radius: 25,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Zoomdata: Tech/Team lead in visualizations team of 4 people', 'Zoomdata: Tech Lead of international FE team of 10 people', 'Leadership and people management certification']
        },
        {
            id: 19,
            title: 'Scrum Master role',
            radius: 20,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Zoomdata: Scrum Master in visualizations team of 4 people', 'ICAgile sertification']
        },
        {
            id: 20,
            title: 'RnD development',
            radius: 25,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Kivu: Browser graphic performance algorithms and approaches research']
        },
        {
            id: 21,
            title: 'Particles project',
            radius: 25,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Zoomdata: High speed WebGL visualizations library', 'Technology developed, presented and sold internally in Zoomdata company']
        },
        {
            id: 22,
            title: 'ForceDirected WebGl graph project',
            radius: 25,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Kivu: High speed WebGL force directed graph library', 'Technology developed, presented and sold internally in Kivu company']
        },
        {
            id: 23,
            title: 'High speed charts constructor',
            radius: 15,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            description: ['Kivu: High speed charts constructor library. Currently under development.']
        },
        {
            id: 24,
            title: 'Metriker Project',
            radius: 15,
            color: '#fc9d03',
            opacity: 1,
            type: 'circle',
            texture: {
                id: 6,
                path: path + 'cv/img/metriker.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'metriker',
                webGlType: 'mono'
            },
            description: ['Own Project: Data analizing, visualizing and reporting system. Currently under development.']
        },
        // Hobbies and aspirations
        {
            id: 25,
            title: 'Hobbies and aspirations',
            radius: 50,
            color: '#f41900',
            opacity: 1,
            type: 'circle',
            fx: window.innerWidth / 2 - 300,
            fy: window.innerHeight / 2 + 150,
            texture: {
                id: 7,
                path: path + 'cv/img/aspirations.png',
                width: 256,
                height: 256,
                type: 'png',
                name: 'aspirations',
                webGlType: 'mono'
            },
            description: ['Everything that drives me forward and gives meaning to every day.']
        },
        {
            id: 26,
            title: 'Family && friends',
            radius: 25,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['Proud to have loving wife and true friends']
        },
        {
            id: 27,
            title: 'World exploration',
            radius: 25,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['I amm an enthusiastic traveler, visited 34 countries and goint to see a lot more.']
        },
        {
            id: 28,
            title: 'Sport',
            radius: 20,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['Gym, diving, running, everything that helps to explore remote corners of the Planet']
        },
        {
            id: 29,
            title: 'Socially valuable projects',
            radius: 20,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['Participating in projects that brings more safety and stability in humans life']
        },
        {
            id: 30,
            title: 'Investments',
            radius: 15,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['New but really interesting topic I want to become an expert']
        },
        {
            id: 31,
            title: 'Cutting edge technologies',
            radius: 20,
            color: '#1d67b2',
            opacity: 1,
            type: 'circle',
            description: ['Robotics, spase engines, deep water exploratory equipment, newest programming features, all this drives me to learn new and improve my engineering skills.']
        },
    ],
    edges: [
        // Main
        {
            id: 0,
            type: 'line',
            head: 0,
            tail: 1,
            target: 0,
            source: 1,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 220
        },
        // Engineering toolkit
        {
            id: 1,
            type: 'line',
            head: 1,
            tail: 2,
            target: 1,
            source: 2,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 2,
            type: 'line',
            head: 1,
            tail: 3,
            target: 1,
            source: 3,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 3,
            type: 'line',
            head: 1,
            tail: 4,
            target: 1,
            source: 4,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 4,
            type: 'line',
            head: 1,
            tail: 5,
            target: 1,
            source: 5,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 5,
            type: 'line',
            head: 1,
            tail: 6,
            target: 1,
            source: 6,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 6,
            type: 'line',
            head: 1,
            tail: 7,
            target: 1,
            source: 7,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 7,
            type: 'line',
            head: 1,
            tail: 7,
            target: 1,
            source: 7,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 8,
            type: 'line',
            head: 1,
            tail: 8,
            target: 1,
            source: 8,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 9,
            type: 'line',
            head: 1,
            tail: 9,
            target: 1,
            source: 9,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 10,
            type: 'line',
            head: 1,
            tail: 10,
            target: 1,
            source: 10,
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        // Infrastructure & management tools
        {
            id: 11,
            type: 'line',
            head: 0,
            tail: 11,
            target: 0,
            source: 11,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 220
        },
        {
            id: 12,
            type: 'line',
            head: 11,
            tail: 12,
            target: 11,
            source: 12,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 13,
            type: 'line',
            head: 11,
            tail: 13,
            target: 11,
            source: 13,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 14,
            type: 'line',
            head: 11,
            tail: 14,
            target: 11,
            source: 14,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 15,
            type: 'line',
            head: 11,
            tail: 15,
            target: 11,
            source: 15,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 16,
            type: 'line',
            head: 11,
            tail: 16,
            target: 11,
            source: 16,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        // Leadership && selling skills
        {
            id: 17,
            type: 'line',
            head: 0,
            tail: 17,
            target: 0,
            source: 17,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 220
        },
        {
            id: 18,
            type: 'line',
            head: 17,
            tail: 18,
            target: 17,
            source: 18,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 19,
            type: 'line',
            head: 17,
            tail: 19,
            target: 17,
            source: 19,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 20,
            type: 'line',
            head: 17,
            tail: 20,
            target: 17,
            source: 20,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 21,
            type: 'line',
            head: 17,
            tail: 21,
            target: 17,
            source: 21,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 22,
            type: 'line',
            head: 17,
            tail: 22,
            target: 17,
            source: 22,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 23,
            type: 'line',
            head: 17,
            tail: 23,
            target: 17,
            source: 23,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 24,
            type: 'line',
            head: 17,
            tail: 24,
            target: 17,
            source: 24,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        // Hobbies and aspirations
        {
            id: 25,
            type: 'line',
            head: 0,
            tail: 25,
            target: 0,
            source: 25,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 220
        },
        {
            id: 26,
            type: 'line',
            head: 25,
            tail: 26,
            target: 25,
            source: 26,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 27,
            type: 'line',
            head: 25,
            tail: 27,
            target: 25,
            source: 27,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 28,
            type: 'line',
            head: 25,
            tail: 28,
            target: 25,
            source: 28,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 29,
            type: 'line',
            head: 25,
            tail: 29,
            target: 25,
            source: 29,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 30,
            type: 'line',
            head: 25,
            tail: 30,
            target: 25,
            source: 30,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
        {
            id: 31,
            type: 'line',
            head: 25,
            tail: 31,
            target: 25,
            source: 31,
            //color: '#4caf50',
            color: '#1ac3cc',
            width: 5,
            opacity: 0.4,
            leftArrow: false,
            rightArrow: false,
            distance: 120
        },
    ]
};

export {graphData};